version: "2"

services:
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
     KAFKA_LISTENERS: 'PLAINTEXT://:9092'
     KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
     KAFKA_REST_LISTENERS: http://0.0.0.0:9092
    container_name: kafka
    networks:
      - back-tier

  zookeeper:
    container_name: zookeeper
    image: 'wurstmeister/zookeeper'
    ports:
      - '2181:2181'
    networks:
      - back-tier

volumes:
  data-volume:
networks:
  back-tier:
